# Generated by Django 4.2.2 on 2023-07-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_category_notes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
